---
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                                 #
#  ██████╗ ███████╗██████╗  ███████╗██╗  ██╗██╗   ██╗ ██████╗ ██╗      ██████╗  ██████╗██╗  ██╗   #
#  ██╔══██╗██╔════╝██╔══██╗ ██╔════╝██║ ██╔╝╚██╗ ██╔╝ ██╔══██╗██║     ██╔═══██╗██╔════╝██║ ██╔╝   #
#  ██████╔╝█████╗  ██║  ██║ ███████╗█████╔╝  ╚████╔╝  ██████╔╝██║     ██║   ██║██║     █████╔╝    #
#  ██╔══██╗██╔══╝  ██║  ██║ ╚════██║██╔═██╗   ╚██╔╝   ██╔══██╗██║     ██║   ██║██║     ██╔═██╗    #
#  ██║  ██║███████╗██████╔╝ ███████║██║  ██╗   ██║    ██████╔╝███████╗╚██████╔╝╚██████╗██║  ██╗   #
#  ╚═╝  ╚═╝╚══════╝╚═════╝  ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝   #
#                                                                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# You can set the SkyBlock world that the plugin will use in your server by changing this variable.
# It is not recommended to change this in the config.yml.
# It is safer to change this by doing /is setworld in-game.
# The plugin will not function if you manually change this to an incorrect value.
SkyBlockWorld: ""

# The Interval is the distance between each Island.
# A recommended Interval is between 200-500.
# Any farther is useless, and any less may be catastrophic in the plugins current state.
Interval: 300

# The magic cobblestone generator is automatically enabled when you first start up the plugin.
# When enabled cobblestone generators will generate much more than just cobblestone.
# When disabled cobblestone generators will function normally.
# In the future, what the Magic cobblestone generator produces will be customizable.
CobbleGen: true

# You can edit the below values to change what the magic cobblestone generator spawns.
# To edit/add just put a block id into the list. If you want a higher chance of an ore to
# then put it in the list more than one time.
# For example, here is the format for an ore generator that has a 1/5 chance of spawning diamond blocks.
# and a 4/5 chance of spawning cobblestone:
# MagicCobbleGenOres:
#  - 4
#  - 4
#  - 4
#  - 4
#  - 57
MagicCobbleGen Ores:
  - 4
  - 4
  - 21

#The Starting Items are the items in SkyBlock that a player will recieve when they first generate their island.
#These items can be edited in the config here. It is really simple and follows this format: "id, damage, count"
#id is the item id for an item in Minecraft, for example: stone's id is 1
#damage is the data value which cooresponds with each individual id. For example: Red would have the id 35 and the damage 14
#count is pretty simple. It is the amount of each item that the player will recieve. It is NOT recommended to set this number super high.
Starting Items:
  - 79, 0, 2
  - 325, 10, 1
  - 287, 0, 12
  - 351, 15, 2
  - 338, 0, 1
  - 361, 0, 1
  - 81, 0, 1
  - 360, 0, 1
  - 39, 0, 1
  - 40, 0, 1

# There are two values for hunger: on and off. If hunger is off then players will no longer loose hunger
# while they are in the SkyBlock world.
Hunger: on

# There are two values for void: on and off. If void is off then players who fall in the void will not die
# while they are in the SkyBlock world.
Void: on

# There are two values for keep inventory: on and off. If it is on then players who die will not
# lose the items in their inventory.
KeepInventory: off

# This limits the amount of members a player can have on their island. Set the number to 0 to disable
# member limits. The default is a 3 member limit.
MemberLimit: 3
...
