---
Version: 1

Spawn Command: "on" #Turn off if you are using a different plugin that controls spawnpoints.
Spawn Hunger: "off" #Turn on if you want players to lose hunger in the spawn world.
Spawn Damage: "off" #Turn on if you want players to take damange in the spawn world.

Island Hunger: "on" #Turn off if you do not want players to lose hunger in the SkyBlock world.
Island PVP: "off" #Turn on if you want PVP to be enabled on SkyBlock islands.

Generator Ores:
  #COBBLESTONE
  4: 60
  #COAL
  16: 8
  #LAPIS
  21: 8
  #REDSTONE
  73: 8
  #IRON
  15: 7
  #GOLD
  14: 4
  #DIAMOND
  56: 3
  #EMERALD
  129: 2


Starting Items:
  - 79, 0, 2
  - 325, 10, 1
  - 287, 0, 12
  - 351, 15, 2
  - 338, 0, 1
  - 361, 0, 1
  - 81, 0, 1
  - 360, 0, 1
  - 39, 0, 1
  - 40, 0, 1

Island Zone:
  0: 0
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0

Zone World: "world" #Set this to the world where your custom island template resides.

Island Interval: 600
Island Size: 100
Island Spawn Y: 26
